#!/bin/sh
#
# Format, lint and test the entire project

find src/ tests/ -name \*.py | entr -s '
    # Stop on first error
    set -e

    print_header () {
        : "${COLUMNS:=79}"
        set -- " $* "
        while test ${#1} -lt $((COLUMNS - 1)); do
            set -- "=${1}="
        done
        test ${#1} -lt $COLUMNS && set -- "${1}="
        printf "\033[1m%s\033[0m\n" "$1"  # Bold
    }

    # Set up virtual environment
    . .venv/bin/activate

    # Clear screen and scrollback: www.xfree86.org/current/ctlseqs.html
    printf "\033c\033[3J"
    test -n "$TMUX_PANE" && tmux clear -t "$TMUX_PANE"

    # Generate tags for all files: ctags(1)
    find src/ tests/ -name \*.py -exec sh -c '\''
        ctags "$@"
        etags "$@"
    '\'' {} +

    # Format
    print_header "Black"
    black --line-length 90 src/ tests/

    # Lint
    print_header "Flake8"
    flake8 src/ tests/ && echo "No errors to display :)"

    # Type-check
    print_header "MyPy"
    mypy src/

    # Any command-line options will be passed to pytest
    pytest --cov=src/ tests/ '"$*"'
'
